default_context:
  project_name: 'gamereview'
  project_slug: 'gamereview'
  domain_main: 'gamereview.com'
  domain_staging: 'stag.gamereview.com'
  docker_swarm_stack_name_main: 'gamereview-com'
  docker_swarm_stack_name_staging: 'stag-gamereview-com'
  secret_key: 'secretgamereview'
  first_superuser: 'admin@gamereview.com'
  first_superuser_password: 'P@ssw0rd!1!'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.gamereview.com", "https://stag.gamereview.com", "https://gamereview.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@gamereview.com'
  postgres_password: 'P@ssw0rdPostgres1!'
  pgadmin_default_user: 'admin@gamereview.com'
  pgadmin_default_user_password: 'P@ssw0rd!1!'
  traefik_constraint_tag: 'gamereview.com'
  traefik_constraint_tag_staging: 'stag.gamereview.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:P@ssw0rd!1!'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend-gamereview'
  docker_image_celeryworker: 'celeryworker-gamereview'
  docker_image_frontend: 'frontend-gamereview'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
